// <auto-generated />
namespace ShopifyAppManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddAccessCodeToShopifyApp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAccessCodeToShopifyApp));
        
        string IMigrationMetadata.Id
        {
            get { return "201211210245527_AddAccessCodeToShopifyApp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
