// <auto-generated />
namespace ShopifyAppManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenamedfromShopifyAppSitestoShopifyApp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamedfromShopifyAppSitestoShopifyApp));
        
        string IMigrationMetadata.Id
        {
            get { return "201211211631262_Renamed from ShopifyAppSites to ShopifyApp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
